package com.example.demo.dto.request;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Request DTO sent by the frontend on every chat turn.
 * Contains the new user message plus the full conversation history
 * so the LLM has context for each response.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChatMessageRequest {

    /** The user's latest message text. */
    @NotBlank(message = "Message cannot be blank")
    private String message;

    /**
     * Full conversation history (role + content pairs) accumulated so far.
     * The frontend is the source of truth for history.
     */
    private List<ConversationTurn> history;

    /** Unique session identifier generated by the frontend. */
    private String sessionId;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class ConversationTurn {
        /** "user" or "model" */
        private String role;
        private String content;
    }
}
